title: Alisa's blog
SEOTitle: Alisa's blog
header-img: img/avatar.png
description: one coder
keyword: "yuyue, frontend, "
author: alisa
email: yuyue19921120@163.com
language: zh-CN

sidebar: true  #添加侧边栏
sidebar-about-description: "简单的描述一下你自己"
sidebar-avatar: /img/avatar.png

markdown: kramdown
theme: jekyll-theme-architect
